### ISSUE TITLE
Support component customization through CSS variables

### ISSUE THREAD

**Issue by davidruvolo51** [InControlofEffects/iceComponents#19]
## Issue

At the moment, it is a bit tricky to customize the components in this package. Ideally, SCSS variables should be compiled into css roots. Overwriting styles involve knowing the markup (and following pseudo selectors, states, etc.) of the components to properly *override* the default styles.

## What I would like to do

SCSS variables should ideally compiled into CSS roots. In addition, css variables should be kept within the package to prevent overriding other styles. Add a package-level css to the document and assign variables there. For example:

```css
.iceComponents {
    --primary: #2d7ddd;               /* bright navy blue */
    --secondary: #F6AE2D;         /* honey yellow */
}
```

Components should have a standardized schema so that individual components can be customized as well.

```css
.accordion {
    --accordion-primary: var(--primary);
    background-color: var(--accordion-primary);
}
```

**Comment by davidruvolo51** [comment]
This is possible by defining the `index.scss` variables as such.

```scss
$primary: #2d7ddd;

:root {
  --primary: #{$primary};
}
```

Even though this works, the variable names must be "make sense" for the user.

**Comment by davidruvolo51** [comment]
The color palette was restructured using the following schema. These variables are now exposed in css `:root` and were passed down into the components. The naming schema for is still a work in progress.

```scss
// set colors
$primary: #4755a9;

$grey-000: #ffffff;
$grey-050: #f6f6f6;
$grey-100: #e1e1e1;
$grey-200: #cbcbcb;
$grey-300: #b6b6b6;
$grey-400: #a0a0a0;
$grey-500: #8b8b8b;
$grey-600: #757575;
$grey-700: #606060;
$grey-800: #4a4a4a;
$grey-900: #353535;

$error-900: #B93213;
$error-050: #FDEFEC;

:root {
    --primary: #{$primary};
    --error-900: #{$error-900};
    --error-050: #{$error-050};
    --grey-000: #{$grey-000};
    --grey-050: #{$grey-050};
    --grey-100: #{$grey-100};
    --grey-200: #{$grey-200};
    --grey-300: #{$grey-300};
    --grey-400: #{$grey-400};
    --grey-500: #{$grey-500};
    --grey-600: #{$grey-600};
    --grey-700: #{$grey-700};
    --grey-800: #{$grey-800};
    --grey-900: #{$grey-900};
}

```
